### ISSUE TITLE
La tua banca per Android

### ISSUE THREAD

**Issue by FrancYescO** [devadvance/rootcloak#56]
RootCload not working on:
https://play.google.com/store/apps/details?id=com.latuabancaperandroid

The app detect root (also ask for root permission at superSU) and when going to Move and pay > PAyGO (NFC payments) say that is "disabled for security reason" 

this is the log after touching the paygo buytton:
```
06-25 11:48:45.086 E/Xposed  ( 5149): java.lang.ClassCastException: android.app.ContextImpl$ApplicationContentResolver cannot be cast to java.lang.String
06-25 11:48:45.086 E/Xposed  ( 5149): 	at com.devadvance.rootcloak2.RootCloak$13.beforeHookedMethod(RootCloak.java:475)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:720)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at android.provider.Settings$Global.getInt(<Xposed>)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at ams.moveandpaymodule.hce.j.b.a(Unknown Source)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at ams.moveandpaymodule.a.q(Unknown Source)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at ams.moveandpaymodule.a.a(Unknown Source)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at ams.moveandpaymodule.a.r(Unknown Source)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at ams.moveandpaymodule.NfcPaymentActivity.onCreate(Unknown Source)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at android.app.Activity.performCreate(Activity.java:6097)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2440)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at android.app.ActivityThread.access$800(ActivityThread.java:162)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at android.os.Looper.loop(Looper.java:135)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at android.app.ActivityThread.main(ActivityThread.java:5430)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at java.lang.reflect.Method.invoke(Native Method)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
06-25 11:48:45.086 E/Xposed  ( 5149): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
```

LG H815 5.1 Framework v85

**Comment by hikaritenchi** [comment]
Fixed with @pylerSM #57
