### ISSUE TITLE
Conflict with WebView on lollipop 5.1

### ISSUE THREAD

**Issue by abdulmoeedammar** [devadvance/rootcloak#9]
When the target application has a webview, it crashes on the launch.

Following is the exception details, please let me know if any other information is required.

```
05-18 15:23:51.738  22422-22422/com.example.abdulmoeed.webviewtest E/WebViewFactory﹕ error instantiating provider
    java.lang.RuntimeException: Invalid reflection
            at com.android.webview.chromium.WebViewDelegateFactory$Api21CompatibilityDelegate.<init>(WebViewDelegateFactory.java:223)
            at com.android.webview.chromium.WebViewDelegateFactory.createApi21CompatibilityDelegate(WebViewDelegateFactory.java:97)
            at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:97)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.Class.newInstance(Class.java:1606)
            at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:124)
            at android.webkit.WebView.getFactory(WebView.java:2194)
            at android.webkit.WebView.ensureProviderCreated(WebView.java:2189)
            at android.webkit.WebView.setOverScrollMode(WebView.java:2248)
            at android.view.View.<init>(View.java:3588)
            at android.view.View.<init>(View.java:3682)
            at android.view.ViewGroup.<init>(ViewGroup.java:497)
            at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
            at android.webkit.WebView.<init>(WebView.java:544)
            at android.webkit.WebView.<init>(WebView.java:489)
            at android.webkit.WebView.<init>(WebView.java:472)
            at android.webkit.WebView.<init>(WebView.java:459)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
            at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:684)
            at android.view.LayoutInflater.inflate(Unknown Source)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:240)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at com.example.abdulmoeed.webviewtest.MainActivity.onCreate(MainActivity.java:14)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
     Caused by: java.lang.NoSuchMethodException: callDrawGLFunction [long]
            at java.lang.Class.getMethod(Class.java:664)
            at java.lang.Class.getMethod(Class.java:643)
            at com.android.webview.chromium.WebViewDelegateFactory$Api21CompatibilityDelegate.<init>(WebViewDelegateFactory.java:211)
            at com.android.webview.chromium.WebViewDelegateFactory.createApi21CompatibilityDelegate(WebViewDelegateFactory.java:97)
            at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:97)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.Class.newInstance(Class.java:1606)
            at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:124)
            at android.webkit.WebView.getFactory(WebView.java:2194)
            at android.webkit.WebView.ensureProviderCreated(WebView.java:2189)
            at android.webkit.WebView.setOverScrollMode(WebView.java:2248)
            at android.view.View.<init>(View.java:3588)
            at android.view.View.<init>(View.java:3682)
            at android.view.ViewGroup.<init>(ViewGroup.java:497)
            at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
            at android.webkit.WebView.<init>(WebView.java:544)
            at android.webkit.WebView.<init>(WebView.java:489)
            at android.webkit.WebView.<init>(WebView.java:472)
            at android.webkit.WebView.<init>(WebView.java:459)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
            at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:684)
            at android.view.LayoutInflater.inflate(Unknown Source)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:240)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at com.example.abdulmoeed.webviewtest.MainActivity.onCreate(MainActivity.java:14)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
05-18 15:23:51.739  22422-22422/com.example.abdulmoeed.webviewtest D/AndroidRuntime﹕ Shutting down VM
    --------- beginning of crash
05-18 15:23:51.740  22422-22422/com.example.abdulmoeed.webviewtest E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.abdulmoeed.webviewtest, PID: 22422
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.abdulmoeed.webviewtest/com.example.abdulmoeed.webviewtest.MainActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class android.webkit.WebView
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
     Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class android.webkit.WebView
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
            at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:684)
            at android.view.LayoutInflater.inflate(Unknown Source)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:240)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at com.example.abdulmoeed.webviewtest.MainActivity.onCreate(MainActivity.java:14)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
            at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:684)
            at android.view.LayoutInflater.inflate(Unknown Source)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:240)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at com.example.abdulmoeed.webviewtest.MainActivity.onCreate(MainActivity.java:14)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
     Caused by: android.util.AndroidRuntimeException: java.lang.RuntimeException: Invalid reflection
            at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:130)
            at android.webkit.WebView.getFactory(WebView.java:2194)
            at android.webkit.WebView.ensureProviderCreated(WebView.java:2189)
            at android.webkit.WebView.setOverScrollMode(WebView.java:2248)
            at android.view.View.<init>(View.java:3588)
            at android.view.View.<init>(View.java:3682)
            at android.view.ViewGroup.<init>(ViewGroup.java:497)
            at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
            at android.webkit.WebView.<init>(WebView.java:544)
            at android.webkit.WebView.<init>(WebView.java:489)
            at android.webkit.WebView.<init>(WebView.java:472)
            at android.webkit.WebView.<init>(WebView.java:459)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
            at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:684)
            at android.view.LayoutInflater.inflate(Unknown Source)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:240)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at com.example.abdulmoeed.webviewtest.MainActivity.onCreate(MainActivity.java:14)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
     Caused by: java.lang.RuntimeException: Invalid reflection
            at com.android.webview.chromium.WebViewDelegateFactory$Api21CompatibilityDelegate.<init>(WebViewDelegateFactory.java:223)
            at com.android.webview.chromium.WebViewDelegateFactory.createApi21CompatibilityDelegate(WebViewDelegateFactory.java:97)
            at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:97)
            at java.lang.reflect.Constructor.newInstance(Native Method)
```

**Comment by R0nd** [comment]
Same here on 5.0.2

**Comment by pylerSM** [comment]
Are you sure this module causes that?

And the method was renamed in AOSP. https://github.com/android/platform_frameworks_base/commit/680df8d60e3445bd14df902796079d730c283c46

**Comment by abdulmoeedammar** [comment]
I don't have the module installed at the moment, but as far as i can remember, the issue was happening because the module was blocking the support libraries from loading, as it found the 'su' in the file name.

But if you change the simple `contains` to a whole word search the problem goes away.

https://github.com/abdulmoeedammar/rootcloak/commit/cc72cafa8960331abe1ab24e74dd0b510ba49aaa

**Comment by pylerSM** [comment]
Could you please upload your fixed version? or.. Shall I use your patch and do it yourself?

**Comment by me21** [comment]
Someone has already fixed the issue and notified the author. However, the fixed version is kept private, but you can ask for it in PM: http://forum.xda-developers.com/showpost.php?p=62218425&postcount=795
I don't know if the fix by abdulmoeedammar and in my link differ.

**Comment by devadvance** [comment]
I'll merge in the fix by @abdulmoeedammar. I haven't done it yet because ideally I should convert the whole thing to an Android Studio project, since support for ADT in Eclipse is ending.

**Comment by abdulmoeedammar** [comment]
Sorry, I am a little busy these days, so thanks @devadvance, it will be great if you can merge the fix. Also in my for fork I have converted the project to Android Studio, along with a couple of other fixes, please have a look https://github.com/abdulmoeedammar/rootcloak/commits/master

**Comment by hikaritenchi** [comment]
@devadvance I'm that "someone", and I tried contacting you earlier, but didn't get a response. I'd like to help by contributing if you're going to maintain this project, but if not, I'd like to carry on the torch personally.

**Comment by devadvance** [comment]
@hikaritenchi I'm going to attempt to maintain going forward, but having help on this would be awesome. I'm merging in @abdulmoeedammar's fixes (Android Studio + webview fix) right now, and I'll be test the build in the latest Android Studio shortly. I can add you as a collaborator to the repo, an as an author to xposed modules, if you'd like.

**Comment by hikaritenchi** [comment]
@devadvance That would be awesome! Can't wait!

**Comment by devadvance** [comment]
Based on XDA feedback, seems like its working on 5.x, especially after the helpful fixes by a couple people.
